### PR TITLE
Ignore current_user with > 0 params

### LINKED ISSUE #618: custom `current_user` with arity > 0 raises exception
* Airbrake version: 5.5.0
* Ruby version: 2.1.10
* Framework name & version: Rails 4.2

#### Airbrake config

Airbrake.configure do |config|
  config.project_key = 'xxx'
  config.project_id = 'xxx'
  config.host = 'errbit.iexposure.com'
  config.environment = Rails.env == 'production' ? Rails.root.to_s.gsub(/\/home\/rails(?:-staging)?\/(.+?)\..+\z/mi, '\1') : Rails.env
end

#### Description

If you have a `current_user` method in your controller, Airbrake will attempt to call it with 0 arguments, regardless of how many arguments are required.

This is, of course, an edge case, but there are reasons it may be valid (in our case, we have an old app that uses two completely separate sets of user models for admin and client users, so you have to tell current_user which type of user you're looking for)

The simple fix would be to add an arity check before calling current_user:

```ruby
# Note: a method with only optional arguments will have arity == -1
if [-1,0].include(controller.method(:current_user).arity)
  ... # call it, etc.
end
```

### PR DESCRIPTION
**Pull request by mltsy**
Fixes #618 
If there is a current_user method that requires parameters, skip calling it (to avoid crashing the app while reporting an exception)

### CODE REVIEW

**Comment by kyrylo** [comment]
Thanks for the PR and raising this issue!
As of now, this can't be merged because the build needs to be fixed first. One more thing that is missing is a test for this case. That said, if you feel like you don't want to do this work, just let me know and I'll come up with my own PR.

**Comment by mltsy** [comment]
Ah Dang!  Github's online editor must automatically add trailing whitespace, because I could swear I removed that 3 or 4 times!  I've got a few minutes now, I'll try pulling to locally and committing from there to see if that helps.

File: spec/unit/rack/user_spec.rb [hunk 1]
```diff
@@ -65,13 +66,28 @@ def env_for(url, opts = {})
...
           allow(controller).to receive(:current_user) { user }
 
           retval = described_class.extract(env)
           expect(retval).to be_a(described_class)
         end
+
+        context "but it requires parameters" do
+          before do
+            class DummyController
+              def current_user(_)
```
Comment (kyrylo) [inline spec/unit/rack/user_spec.rb]: Please add tests that cover:

* `def current_user(a)`
* `def current_user(a, b)`
* `def current_user(*a)`
* `def current_user(a, *b)`
* `def current_user(a, b, *c, &d)`

File: spec/unit/rack/user_spec.rb [hunk 2]
```diff
@@ -65,13 +66,28 @@ def env_for(url, opts = {})
...
-          env = env_for('/', 'action_controller.instance' => controller)
           allow(controller).to receive(:current_user) { user }
 
           retval = described_class.extract(env)
           expect(retval).to be_a(described_class)
         end
+
+        context "but it requires parameters" do
+          before do
+            class DummyController
```
Comment (kyrylo) [inline spec/unit/rack/user_spec.rb]: Please use Class.new to avoid `Object.send(:remove_const, :DummyController)`.

File: lib/airbrake/rack/user.rb [hunk 3]
```diff
@@ -17,9 +17,15 @@ def self.extract(rack_env)
...
         # Fallback mode (OmniAuth support included). Works only for Rails.
+        user = try_current_user(rack_env)
+        new(user) if user
+      end
+
+      def self.try_current_user(rack_env)
         controller = rack_env['action_controller.instance']
         return unless controller.respond_to?(:current_user)
-        new(controller.current_user) if controller.current_user
+        return unless [-1, 0].include?(controller.method(:current_user).arity)
```
Comment (kyrylo) [inline lib/airbrake/rack/user.rb]: Let's use the following condition:

`return if controller.method(:current_user).arity <= 0`

File: lib/airbrake/rack/user.rb [hunk 4]
```diff
@@ -17,9 +17,15 @@ def self.extract(rack_env)
...
+        controller.current_user
       end
```
Comment (kyrylo) [inline lib/airbrake/rack/user.rb]: Please make this method private ([example](https://github.com/airbrake/airbrake-ruby/blob/a93cd6133f799390086735ddacbee49b8f1286a5/lib/airbrake-ruby/response.rb#L42-L51)).

**Comment by mltsy** [comment]
Uh... I don't think this failure was me - something about a jruby string, and something's up with bundler... ? :)

**Comment by kyrylo** [comment]
Just restarted it. It happens from time to time due to network issues.

**Comment by mltsy** [comment]
Just occurred to me that perhaps the more robust way to handle this would be to just call current_user and rescue if it fails... but then I'm not sure whether that would have unintended consequences either I guess.  Just wanted to mention that in case you prefer it :wink:

File: lib/airbrake/rack/user.rb (hunk 3 above)
Comment (kyrylo) [inline lib/airbrake/rack/user.rb]: I think the condition I suggested is wrong, but I hope you got the idea (no need to use #include and array since we can rewrite it, so it uses comparison).

 ```rb
return if controller.method(:current_user).arity != 0
```

**Comment by kyrylo** [comment]
No, that would be quite inefficient. What we have now looks good, it's just that the condition can be simplified, I think.

**Comment by mltsy** [comment]
Oops!  I didn't realize I had to "submit my review" before all my line comments would post - Sorry!  All those comments were form Friday - suddenly it makes sense that you didn't respond :wink:

File: lib/airbrake/rack/user.rb (hunk 3 above)
Comment (kyrylo) [inline lib/airbrake/rack/user.rb]: Cool, thanks for the explanation. That makes sense, let's leave as is.

**Comment by kyrylo** [comment]
Hah, yeah, it takes a while to get used to the new feature. Thanks for the PR, great work!

**Comment by kyrylo** [comment]
I'm going to release a new version as soon as https://github.com/airbrake/airbrake/pull/624 is closed, which will probably be tomorrow.

**Comment by mltsy** [comment]
Wonderful, thanks! :+1:
