### PR TITLE
rake: suggest how to airbrake:test when current env is ignored

### LINKED ISSUE #521: Test rake task doesn't work for ignored environments
* Airbrake version: 5.0.5
* Ruby version: 2.3.0
* Framework name & version: 4.2.5.1

So far as I can tell, the `rake airbrake:test` rake task does not work if the current environment is an ignored environment.

I'm using rails and I have development as an ignored environment. When I run rake tasks, they run in the development environment by default. However, when I run the test rake task, I get an error:

```
$ bundle exec rake --trace airbrake:test
** Invoke airbrake:test (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute airbrake:test
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/iain/.gem/ruby/2.3.0/gems/airbrake-5.0.5/lib/airbrake/rake/tasks.rb:41:in `block (2 levels) in <top (required)>'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/iain/.gem/ruby/2.3.0/gems/airbrake-5.0.5/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/iain/.rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/iain/.gem/ruby/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/iain/.gem/ruby/2.3.0/bin/rake:23:in `load'
/Users/iain/.gem/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => airbrake:test
```

If I remove development from the ignored environments, it works:

```
$ bundle exec rake --trace airbrake:test
** Invoke airbrake:test (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute airbrake:test
[ruby]
description: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

[rails]
version: 4.2.5.1

[airbrake]
version: 5.0.5

[airbrake-ruby]
version: 1.1.0

[notifiers]
default:
  [#<Airbrake::Config:0x007ff5fc6fd5e8
  @endpoint=
   #<URI::HTTPS https://airbrake.io/api/v3/projects/7534/notices?key=b983b649215dd65f9b464705fbbd1fc5>,
  @environment="development",
  @host="https://airbrake.io",
  @ignore_environments=["test"],
  @logger=
   #<ActiveSupport::Logger:0x007ff5fdbfaa18
    @default_formatter=
     #<Logger::Formatter:0x007ff5fdbfa9a0 @datetime_format=nil>,
    @formatter=
     #<ActiveSupport::Logger::SimpleFormatter:0x007ff5fc385190
      @datetime_format=nil,
      @thread_key="activesupport_tagged_logging_tags:70347237632200">,
    @level=0,
    @local_levels=
     #<Concurrent::Map:0x007ff5fdbfa860
      @backend={},
      @default_proc=nil,
      @write_lock=#<Thread::Mutex:0x007ff5fdbfa7e8>>,
    @logdev=
     #<Logger::LogDevice:0x007ff5fdbfa950
      @dev=#<File:/Users/iain/Work/airbrake-test/log/development.log>,
      @filename=nil,
      @mon_count=0,
      @mon_mutex=#<Thread::Mutex:0x007ff5fdbfa900>,
      @mon_owner=nil,
      @shift_age=nil,
      @shift_size=nil>,
    @progname=nil>,
  @project_id=7534,
  @project_key="b983b649215dd65f9b464705fbbd1fc5",
  @proxy={},
  @queue_size=100,
  @root_directory=#<Pathname:/Users/iain/Work/airbrake-test>,
  @timeout=nil,
  @workers=1>,
 #<Airbrake::FilterChain:0x007ff5fc6fcf08
  @filters=
   [#<Proc:0x007ff5fc6fce68@/Users/iain/.gem/ruby/2.3.0/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/filter_chain.rb:81>,
    #<Proc:0x007ff5fda48b98@/Users/iain/.gem/ruby/2.3.0/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/filter_chain.rb:25>,
    #<Proc:0x007ff5fda48bc0@/Users/iain/.gem/ruby/2.3.0/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/filter_chain.rb:10>,
    #<Proc:0x007ff5fc6fcdf0@/Users/iain/.gem/ruby/2.3.0/gems/airbrake-ruby-1.1.0/lib/airbrake-ruby/filter_chain.rb:71>]>]


The output above contains useful information about your environment. Our support
team may request this information if you have problems using the Airbrake gem;
we would be really grateful if you could attach the output to your message.

The test exception was sent. Find it here: https://airbrake.io/locate/1631245824838526029
```

You can reproduce this error easily by doing the following:

```
$ rails new --skip-bundle airbrake-test
...
$ cd airbrake-test
$ echo "gem 'airbrake'" >> Gemfile
$ bundle install
...
$ rails g airbrake <project_id> <project_key>
...
$ bundle exec rake test # should work
...
$ sed -i '' 's/.*c.ignore_environments.*/c.ignore_environments = %w(development test)/g' config/initializers/airbrake.rb
$ bundle exec rake test # BOOM!
...
```

As rake tasks are usually run in the development environment, I would have expected the test task to work in development too.

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #521 (Test rake task doesn't work for ignored environments)

### CODE REVIEW

**Comment by kyrylo** [comment]
PTAL

File: lib/airbrake/rake/tasks.rb [hunk 1]
```diff
@@ -40,6 +41,15 @@
 
 The test exception was sent. Find it here: #{response['url']}
 OUTPUT
+    else
```
Comment (shifi) [inline lib/airbrake/rake/tasks.rb]: So response will not be present **only** when you ignore env from which you're running the task?

Comment (kyrylo) [inline lib/airbrake/rake/tasks.rb]: Yes. Also if you have filters that ignore notices such as this one.
I agree, it's not crystal clear, but I like the simplicity of the current code.

Comment (shifi) [inline lib/airbrake/rake/tasks.rb]: I would mention this filters here in output just to avoid confusion.

**Comment by shifi** [comment]
LGTM

**Comment by shime** [comment]
LGTM

File: lib/airbrake/rake/tasks.rb (hunk 1 above)
Comment (kyrylo) [inline lib/airbrake/rake/tasks.rb]: Added this information. Thanks!
