### PR TITLE
rake: fix parsing variable in Heroku deploy hook

### LINKED ISSUE #574: rake airbrake:install_heroku_deploy_hook parsing env vars inocrrectly
bundle exec rake airbrake:install_heroku_deploy_hook HEROKU_APP=<APP_NAME> --trace
** Invoke airbrake:install_heroku_deploy_hook (first_time)
** Execute airbrake:install_heroku_deploy_hook
rake aborted!
ArgumentError: odd number of arguments for Hash

Error place:
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rake/tasks.rb#L95

Hash["1", "2", "3"]
ArgumentError: odd number of arguments for Hash

The reason is that i have in config vars values which contain "=" sign and splitting return 3 objects 
i.e:

`SPREADSHEET_URL:  https://docs.google.com/spreadsheet/pub?key=111111111111111111111111`

Fix would be appreciated

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #574 (rake airbrake:install_heroku_deploy_hook parsing env vars
inocrrectly)

### CODE REVIEW

File: lib/airbrake/rake/tasks.rb [hunk 1]
```diff
@@ -92,7 +92,7 @@
     end
 
     heroku_env = config.each_line.with_object({}) do |line, h|
-      h.merge!(Hash[*line.rstrip.split('=')])
+      h.merge!(Hash[*line.rstrip.split.flat_map { |v| v.split('=', 2) }])
```
Comment (zefer) [inline lib/airbrake/rake/tasks.rb]: This looks like it deserves a test :)

Comment (kyrylo) [inline lib/airbrake/rake/tasks.rb]: I feel like it's too trivial.

Comment (zefer) [inline lib/airbrake/rake/tasks.rb]: The test should be simple enough to add to https://github.com/airbrake/airbrake/blob/master/spec/unit/rake/tasks_spec.rb, and it will make this code much easier to understand and work with.

Comment (kyrylo) [inline lib/airbrake/rake/tasks.rb]: Added test by https://github.com/airbrake/airbrake/pull/577/commits/f007452cab20bde7f4cce3c52c71bc3772f1a040

Comment (zefer) [inline lib/airbrake/rake/tasks.rb]: It looks like the new test passes without this fix.

Comment (kyrylo) [inline lib/airbrake/rake/tasks.rb]: Oops, fixed by https://github.com/airbrake/airbrake/pull/577/commits/d868a3763e0d8b2e043ee951922ffb56a9f787b9.

**Comment by kyrylo** [comment]
PTAL

**Comment by zefer** [comment]
LGTM
